apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  # stroage는 실제로 사용하는 용량을 제한하는 것이 아니라 쓸 수 있는 양을 레이블로 붙이는 것과 같음.
  # 이는 현재 스토리지가 단순히 NFS로 설정되었기 때문
  capacity:
    storage: 100Mi
  # PV를 어떤 방식으로 사용할지를 정의한 부분.
  # ReadWriteMany는 여러 개의 노드가 읽고 쓸 수 있도록 마운트하는 옵션
  # ReadWriteOnce(하나의 노드에서만 볼륨을 읽고 쓸 수 있게 마운트)
  # ReadOnlyMany(여러 개의 노드가 읽도록 마운트)
  accessModes:
    - ReadWriteMany
  # persistentVolumeReclaimPolicy는 PV가 제거됐을 때 작동하는 방법을 정의하는 것
  # Retain을 사용하여 유지
  # Delete, Recycle, Deprecated 옵션이 있음
  persistentVolumeReclaimPolicy: Retain
  # NFS 서버의 연결 위치에 대한 설정
  nfs:
    server: 192.168.56.10
    path: /nfs_shared